### Acquiring Financial Data

#### Sources

> https://ranaroussi.github.io/yfinance/

> https://pythonfintech.com/articles/how-to-download-market-data-yfinance-python/

In [1]:
# test to see if the path is correct
import sys
print(sys.executable)

C:\Users\mrgnp\Documents\generalised-research\.venv\Scripts\python.exe

In [3]:
# set up 
import pandas as pd 
import seaborn as sns
import matplotlib.pyplot as plt

Layout

* `Getting data from Yahoo Finance`
* Getting data from Nasdaq Data Link
* Getting data from Intrinio
* Getting data from Alpha Vantage
* Getting data from CoinGecko

#### Getting data from Yahoo Finanace

> %pip install yfinance

In [3]:
import yfinance as yf

In [5]:
# download the data

df = yf.download("AAPL",
                start="2011-01-01",
                end="2021-12-31",
                progress=False)

In [8]:
# inspect the downloaded data:
print(f'Download {len(df)} rows of data.')
df.head(5)

Download 2768 rows of data.

Price           Close       High       Low       Open     Volume
Ticker           AAPL       AAPL      AAPL       AAPL       AAPL
Date
2011-01-03   9.865818   9.886474  9.724224   9.748172  445138400
2011-01-04   9.917308   9.953529  9.823310   9.951733  309080800
2011-01-05   9.998432  10.008610  9.863723   9.865220  255519600
2011-01-06   9.990352  10.035853  9.965505  10.019987  300428800
2011-01-07  10.061897  10.068782  9.935569   9.998135  311931200

#### Additional Features

* We can download information for multiple tickers at once by providing a list of tickers `(["AAPL", "MSFT"])` or multiple tickers as a string `("AAPL MSFT")`.
* We can set `auto_adjust=True` to download only the adjusted prices.
* We can additionally download dividends and stock splits by setting `actions='inline'`. Those
actions can also be used to manually adjust the prices or for other analyses.
* Specifying `progress=False` disables the progress bar.
* The `interval` argument can be used to download data in different frequencies. We could also
download intraday data as long as the requested period is shorter than 60 days.

---

#### Using multi_level_index=False to sort the headers

Currently, `multi_level_index` is by default `True`, so you get this when you download data:

```text
Price       Close    High    Low    Open    Volume
Ticker      AAPL     AAPL    AAPL   AAPL    AAPL
Date
```
When you use:

```python
multi_level_index=False
```
You should look more like this:

```text
Date          Open       High       Low        Close      Volume
2011-01-03    ...
2011-01-04    ...
2011-01-05    ...
```

In [14]:
df = yf.download(
    "AAPL", # ticker
    start="2011-01-01",
    end="2021-12-31",
    progress=False, # disable displaying the progress bar for downloading data
    multi_level_index=False, # fixes the headers
)

df.head()

                Close       High       Low       Open     Volume
Date
2011-01-03   9.865818   9.886474  9.724224   9.748172  445138400
2011-01-04   9.917308   9.953529  9.823310   9.951733  309080800
2011-01-05   9.998432  10.008610  9.863723   9.865220  255519600
2011-01-06   9.990352  10.035853  9.965505  10.019987  300428800
2011-01-07  10.061897  10.068782  9.935569   9.998135  311931200

### Lower the columns so the match Quant-Connects

In [16]:
df.columns = df.columns.str.lower()
df.head()

                close       high       low       open     volume
Date
2011-01-03   9.865818   9.886474  9.724224   9.748172  445138400
2011-01-04   9.917308   9.953529  9.823310   9.951733  309080800
2011-01-05   9.998432  10.008610  9.863723   9.865220  255519600
2011-01-06   9.990352  10.035853  9.965505  10.019987  300428800
2011-01-07  10.061897  10.068782  9.935569   9.998135  311931200

In [20]:
# accessing the columns
close_price = df['close']
close_price.head()

Date
2011-01-03     9.865818
2011-01-04     9.917308
2011-01-05     9.998432
2011-01-06     9.990352
2011-01-07    10.061897
Name: close, dtype: float64

---

### What does `prepost=True` actually mean?

For a US stock or ETF such as AAPL or QQQ, there are three trading sessions:

```text
Pre-market      Regular market        After-hours
4:00–9:30 ET    9:30–16:00 ET         16:00–20:00 ET
      │                │                     │
      └──────── extended trading ────────────┘
```

Nasdaq describes pre-market as 4:00–9:30 ET and after-hours as 16:00–20:00 ET. These are trading sessions before and after the main exchange session.

so:
```python
prepost=False
```
means:

> Give me the normal/regular trading session

whereas:
```text 
prepost=True
```
means:
> Include the pre-market and after-hours trades as well
---

#### The QuantConnect comparison

QuantConnect also defaults US Equity subscriptions to regular market hours. You have to explicitly request:

```python
extended_market_hours=True
```
conceptually:
```text
_______________________________________________
  yfinance        QuantConnect                
_______________________________________________
| prepost=False | extended_market_hours=False |
| prepost=True  | extended_market_hours=True  |
-
```

Next Learn about Intervals and downloading data!