## Save and Load Market Data

---

In [ ]:
# TODO 1: Imports
# TODO 2: Create a Clean DataFrame
# TODO 3: Create the Data Path
# TODO 4: Save the DataFrame to CSV
# TODO 5: Check the Saved File
# TODO 6: Load the CSV
# TODO 7: Restore the Datetime Index
# TODO 8: Verify the Loaded Data

In [7]:
# TODO 1: import whats needed
from pathlib import Path
import pandas as pd
import yfinance as yf

In [8]:
# TODO 2: Create a clean DataFrame

ICKER = "QQQ"

df = yf.download(
    TICKER,
    period="5d",
    interval="1m", 
    auto_adjust=True,
    prepost=False, 
    multi_level_index=False,
    progress=False
)

# access the columns, treat those columns as a string and convert to lower case
df.columns = df.columns.str.lower()
# reorder the order in the df 
df = df[["open", "high", "low", "close", "volume"]]

# convert the index to UTC timezone
df.index = df.index.tz_convert("UTC")

# Quantconnect works with the bar endtime, so we need to shift the index by 1 minute
bar_length = pd.Timedelta(minutes=1)
df.index = df.index + bar_length

# match the index name to quantconnects df
df.index.name = "time"
df = df.sort_index()

In [6]:
df.head()

,open,high,low,close,volume
time,,,,,
2026-09-02 13:31:00+00:00,707.109985,707.109985,705.770020,706.320007,1624092
2026-09-02 13:32:00+00:00,706.250000,706.739990,705.820007,706.005005,185961
2026-09-02 13:33:00+00:00,706.020020,706.729614,706.000000,706.625000,71144
2026-09-02 13:34:00+00:00,706.700012,706.809998,706.200012,706.450012,90534
2026-09-02 13:35:00+00:00,706.450012,706.830017,706.349976,706.690002,81950

In [9]:
# TODO 3: Create the file path 

data_folder = Path("../data")

In [10]:
# add the file name to the file path
file_path = data_folder / "qqq_1min.csv"

In [12]:
print(data_folder)
print(file_path)

..\data
..\data\qqq_1min.csv

In [14]:
# TODO 4: save the dataframe to a csv

df.to_csv(file_path)

Does a saved dataset already exist?

```text
YES → load/update it
NO  → download a new one
```

In [ ]:
# TODO 5: Check the Saved File
file_path.exists()

True

In [22]:
# TODO 6: Load the CSV
loaded_df = pd.read_csv(file_path)
loaded_df.head()

,time,open,high,low,close,volume
0,2026-09-02 13:31:00+00:00,707.109985,707.109985,705.770020,706.320007,1624092
1,2026-09-02 13:32:00+00:00,706.250000,706.739990,705.820007,706.005005,185961
2,2026-09-02 13:33:00+00:00,706.020020,706.729614,706.000000,706.625000,71144
3,2026-09-02 13:34:00+00:00,706.700012,706.809998,706.200012,706.450012,90534
4,2026-09-02 13:35:00+00:00,706.450012,706.830017,706.349976,706.690002,81950

In [21]:
# TODO 7: Restore the Datetime Index
loaded_df = pd.read_csv(
    file_path,
    parse_dates= ["time"], 
    index_col= "time",
)

# TODO 8: Verify the Loaded Data
loaded_df.head()

,open,high,low,close,volume
time,,,,,
2026-09-02 13:31:00+00:00,707.109985,707.109985,705.770020,706.320007,1624092
2026-09-02 13:32:00+00:00,706.250000,706.739990,705.820007,706.005005,185961
2026-09-02 13:33:00+00:00,706.020020,706.729614,706.000000,706.625000,71144
2026-09-02 13:34:00+00:00,706.700012,706.809998,706.200012,706.450012,90534
2026-09-02 13:35:00+00:00,706.450012,706.830017,706.349976,706.690002,81950

In [24]:
loaded_df.shape

(1848, 6)

In [25]:
df.shape

(1848, 5)